@startuml
scale 350 width

[*] --> creado : jugador ingresa al juego
creado --> movimiento : comienza a moverse
movimiento --> arriboAEsquina : arriba a la esquina elegida
arriboAEsquina -right-> trancitaCuadra : trancita cuadra
state c <<choice>>
trancitaCuadra --> c : llego a la meta final?
c --> [*] : si
c --> arriboAEsquina : no

}
@enduml