@startuml


         class Esquina {
           - aristaNorte : Interseccion
           - aristaSur : Interseccion
           - aristaOeste : Interseccion
           - aristaEste : Interseccion

        }



@enduml
