@startuml

package Model {
        class Jugador {
        		- movimientos : int
        		
                + sorpresaFavorable() : void
                + sorpresaDesfavorable() : void
                + sorpresaCambiodeVehiculo() : void
                + penalizacionPozo(): void
	            + penalizacionPiquete() : void
	            + penalizacionControl() : void
        }
}

@enduml
