@startuml

    class Esquina {
         -cuadras : HashMap<String, Cuadra>
         +moverVehiculo(jugador: Jugador, direccion: String)
         +insertarCuadra(direccion: String, cuadra: Cuadra)
    }

@enduml
