@startuml

    class Esquina {
         -cuadras : HashMap<String, Cuadra>
         +moverVehiculo(jugador: Jugador, direccion: Direccion)
         +insertarCuadra(direccion: Direccion, cuadra: Cuadra)
    }

@enduml
