@startuml

    class Jugador {
        - movimientos : Int
        - vehiculo : Vehiculo
        + getMovimientos(): Int
        + getVehiculo(): Vehiculo
        + incrementarMovimientos(movimientos : Int)
        + moverEnDireccion(direccion : String)
        + posicionActual(): Esquina
        + spawnearVehiculoEn(unaEsquina : Esquina)
        + aplicarSorpresaCambioVehiculo()
        + sorpresaFavorable()
        + sorpresaDesfavorable()
        + atravezarControlPolicial()

    }

@enduml