@startuml

package Sorpresa {
       interface Sorpresa {
                

        }
        class Favorable {

                }
        class Desfavorable {

                }
        class CambioDeVehiculo {

                }
}

Sorpresa <|.. Favorable
Sorpresa <|.. Desfavorable
Sorpresa <|.. CambioDeVehiculo

@enduml
