@startuml

package Model {
        abstract  class Sorpresa {
                
                + {abstract} aplicarEfecto(Jugador): void
        }
}

package Model {
        class Favorable {
               + aplicarEfecto(Jugador): void
        }
}

package Model {
        class Desfavorable {
               + aplicarEfecto(Jugador): void
        }
}

package Model {
        class CambioDeVehiculo {
             + aplicarEfecto(Jugador): void
        }
}

Sorpresa <|-- Favorable
Sorpresa <|-- Desfavorable
Sorpresa <|-- CambioDeVehiculo

@enduml
