@startuml
Actor test
test -> CuatroPorCuatro : mover(Esquina)
CuatroPorCuatro -> Esquina: arribar(CuatroPorCuatro)
Esquina -> Cuadra: trancita(CuatroPorCuatro)
Cuadra -> CuatroPorCuatro: atravezarCuadra()
CuatroPorCuatro --> Cuadra
Cuadra -> Pozo: penalizar(CuatroPorCuatro)
Pozo -> CuatroPorCuatro: atravezarPozo()

CuatroPorCuatro -> CuatroPorCuatro : pozosAtravezados++
note left
    pozosAtravezados < 3
end note

CuatroPorCuatro -> Jugador: incrementarMovimientos(0)
Jugador --> CuatroPorCuatro
CuatroPorCuatro --> Pozo
Pozo --> Cuadra
Cuadra --> Esquina
Esquina --> CuatroPorCuatro
CuatroPorCuatro --> test
@enduml