@startuml
title: una4x4AtraviesaCiudadYSeEncuentraConUnPozoYNoEsPenalizada

Actor test
test -> ":Juego" : moverJugadorEnDireccion(Este)
":Juego" -> ":Jugador"  : moverEnDireccion(Este)
":Jugador"  -> ":Vehiculo" : moverseAEsquina(this, Este)
":Vehiculo" -> "esquinaActual: Esquina" : moverVehiculo(jugador, Este)
"esquinaActual: Esquina" -> "esquinaActual: Esquina" : getCuadra(Este)
"esquinaActual: Esquina" -> ":Jugador" : incrementarMovimientos(1)
return

"esquinaActual: Esquina" -> "cuadraAdirijirse: Cuadra" : moverVehiculo(jugador, this)
"cuadraAdirijirse: Cuadra" -> "cuadraAdirijirse: Cuadra" : obtenerEsquinaOpuesta(esquinaInicio)
"cuadraAdirijirse: Cuadra" -> ":Pozo" : afectarJugador(jugador, esquinaInicio, esquinaOpuesta)

":Pozo" -> ":Jugador" : getVehiculo()
return vehiculo
":Pozo" -> ":Vehiculo" : chocarContraPozo(jugador)
":Vehiculo" -> ":EstadoCuatroPorCuatro" : chocarContraPozo(jugador)
":EstadoCuatroPorCuatro" -> ":EstadoCuatroPorCuatro" : pozosAtravezados++
":EstadoCuatroPorCuatro" --> ":Vehiculo"
":Vehiculo" --> ":Pozo"

":Pozo" --> "cuadraAdirijirse: Cuadra" : esquinaDestino = esquinaOpuesta
"cuadraAdirijirse: Cuadra" -> ":Jugador" : setEsquinaActual(esquinaDestino)
":Jugador" -> ":Vehiculo" : setEsquinaActual(esquinaDestino)

return
":Jugador" --> "cuadraAdirijirse: Cuadra"
"cuadraAdirijirse: Cuadra" --> "esquinaActual: Esquina"
"esquinaActual: Esquina" --> ":Vehiculo"
":Vehiculo" --> ":Jugador"
":Jugador" --> ":Juego"
":Juego" --> test

@enduml