@startuml
Actor test
test -> Moto : mover(Esquina)
Moto -> Esquina: arribar(Moto)
Esquina -> Cuadra: trancita(Moto)

Cuadra -> Pozo: penalizar(Moto)
Pozo -> Moto: penalizarConductor(3)
Moto-> Jugador: turnosPenalizados(3)
loop 3 times
Jugador -> Penalizado: new()
Penalizado --> Jugador
end
Jugador --> Moto
Moto --> Pozo
Pozo --> Cuadra
Cuadra --> Esquina
Esquina --> Moto
Moto --> test

@enduml