@startuml
title: unAutoAtraviesaLaCiudadYEncuentraUnaSorpresaCambioDeVehículo


Actor test
test -> ":Juego" : moverJugadorEnDireccion(Este)
":Juego" -> ":Jugador"  : moverEnDireccion(Este)
":Jugador"  -> ":Vehiculo" : moverseAEsquina(this, Este)
":Vehiculo" -> "esquinaActual: Esquina" : moverVehiculo(jugador, Este)
"esquinaActual: Esquina" -> "esquinaActual: Esquina" : getCuadra(Este)
"esquinaActual: Esquina" -> ":Jugador" : incrementarMovimientos(1)
return

"esquinaActual: Esquina" -> "cuadraAdirijirse: Cuadra" : moverVehiculo(jugador, this)
"cuadraAdirijirse: Cuadra" -> "cuadraAdirijirse: Cuadra" : obtenerEsquinaOpuesta(esquinaInicio)
"cuadraAdirijirse: Cuadra" -> ":SorpresaCambioDeVehiculo" : afectarJugador(jugador, esquinaInicio, esquinaOpuesta)

":SorpresaCambioDeVehiculo" -> ":Jugador" : aplicarSorpresaCambioVehiculo()
":Jugador" -> ":Vehiculo" : aplicarSorpresaCambioVehiculo()
":Vehiculo" -> ":EstadoAuto" :  aplicarSorpresaCambioVehiculo()
":EstadoAuto" --> ":Vehiculo" : this.estadoVehiculo = EstadoCuatroPorCuatro
":Vehiculo" --> ":Jugador"
":Jugador" --> ":SorpresaCambioDeVehiculo"

":SorpresaCambioDeVehiculo" --> "cuadraAdirijirse: Cuadra" : esquinaDestino = esquinaOpuesta
"cuadraAdirijirse: Cuadra" -> ":Jugador" : setEsquinaActual(esquinaDestino)
":Jugador" -> ":Vehiculo" : setEsquinaActual(esquinaDestino)

return
":Jugador" --> "cuadraAdirijirse: Cuadra"
"cuadraAdirijirse: Cuadra" --> "esquinaActual: Esquina"
"esquinaActual: Esquina" --> ":Vehiculo"
":Vehiculo" --> ":Jugador"
":Jugador" --> ":Juego"
":Juego" --> test

@enduml